### ISSUE TITLE
windows下会卡死

### ISSUE THREAD

**Issue by zhaoqin102** [mrshawnho/ideaagent#1]
windows下面执行到import maven projects的时候就会卡死

**Comment by mrshawnho** [comment]
@zhaoqin102 win10 idea 2017 3.1 测试没问题哦

**Comment by zhaoqin102** [comment]
@mrshawnho 我再试试

**Comment by zhaoqin102** [comment]
@mrshawnho 好的,我试试.生成的隐藏文件有办法指定目录吗?

**Comment by mrshawnho** [comment]
@zhaoqin102 默认存储在用户目录下的 win下应该是C:\Users\***\ideaagent.log

**Comment by zhaoqin102** [comment]
@mrshawnho  .vertx 这个文件夹是直接生成在桌面了

**Comment by mrshawnho** [comment]
@zhaoqin102 可参考 [disabling_file_caching_on_disk](http://vertx.io/docs/vertx-web/java/#_disabling_file_caching_on_disk)

**Comment by hysys32** [comment]
不知为何 设置完后 IDEA彻底打不开了。。。。。Windows环境。。。

**Comment by mrshawnho** [comment]
@hysys32 能贴出您的IDEA VM配置么

**Comment by zhaoqin102** [comment]
@hysys32 -javaagent:D:/JetBrains/ideaagent.jar 需要指定你包存放的位置

**Comment by zhaoqin102** [comment]
@mrshawnho 我这边应该是假死,等一段时间就好了

**Comment by mustkass** [comment]
@mrshawnho 
我今天编译的时候也提示
`Error:(19, 30) Kotlin: Unresolved reference: BASE64Decoder`
然后就在网上了一个`sun.misc.BASE64Decoder.jar` 包，把包添加到lib 后还是IDEA 上显示还是红色，就试着打了一个BASE64Decoder，然后发现`Decoder.BASE64Decoder`包， 然后方法都一样， 就编译了。
不知道是不是编译的方法不对，在vm 里添加`-javaagent:D:/ideaagent.jar` IDEA 就打不开了，望看一下。


![Uploading 456.png…]()

**Comment by mrshawnho** [comment]
@mustkass [release](https://github.com/mrshawnho/ideaagent/releases) 有编译好的可以直接下载使用 您是如何编译的呢 请使用 mvn clean package 打包试试

**Comment by mustkass** [comment]
@mrshawnho 好的， 我去试试，谢谢你了

**Comment by mustkass** [comment]
@mrshawnho  使用`mvn clean package` 打包提示：`Unresolved reference: BASE64Decoder`。
然后使用编译已经可以了，谢谢你了

**Comment by Arowa-Z** [comment]
同 Windows下会卡死，IDEA点不动 但是 又没有显示 未响应  只能任务管理器强制结束，ideaagent.log也没啥错误信息。没找到 复现的步骤 QwQ，反正 一直用会卡死
