### ISSUE TITLE
ideaagent-1.12.zip已失效.

### ISSUE THREAD

**Issue by renruiquan** [mrshawnho/ideaagent#10]
打开Intellij Idea 2017.3.4以后提示A network is required to use Mybatis plugin. You can configure a proxy if you can't access the internet.

**Comment by mrshawnho** [comment]
亲测能用
@renruiquan 
删除 .IntelliJIdea2017.3\system\tasks\cacerts
重启 会弹个窗选择 <接受>

**Comment by HowLow** [comment]
为什么我装anagent的时候跟我讲 fail to load。。

**Comment by mrshawnho** [comment]
@HowLow 上图看看

**Comment by renruiquan** [comment]
@mrshawnho 我把 [.IntelliJIdea2017.3\system\下面所有文件删除，并重启都不行，我的tasks目录下面是空的，没有文件，cacerts和tasks目录是同级。]

**Comment by zhaojunliing** [comment]
好像高版本的mybatis pluis没办法初始化

**Comment by mrshawnho** [comment]
@renruiquan ideaagent会打开本地7848端口 确认未被占用 启动idea后试试能不能访问  https://localhost:7848/q

**Comment by uncle-link** [comment]
我打开7848那个地址返回一段hash, 但是idea的mybatis 插件没有生效啊! 我是线装mybatis插件然后装你的破解, 当时能用, 然后我合上电脑, 过了一会儿回来,打开idea中的那些插件效果一闪都没了不知道为啥

**Comment by renruiquan** [comment]
@mrshawnho 本地7848端口确认没有被占用，启动IDEA也不能访问https://localhost:7848/q

**Comment by alecthw** [comment]
更新3.55了，直接提示license过期了。。。
