### ISSUE TITLE
Windows10 IDEA17.3.1 版本报错

### ISSUE THREAD

**Issue by mustkass** [mrshawnho/ideaagent#2]
大概前几天更新了一次，然后打开IDEA的时候会提示有错误，错误如下
![comments](http://i2.bvimg.com/624971/ce1ea05354bceb4d.png)
![details](http://i2.bvimg.com/624971/52f036d4310e3e4a.png)
望看一下

**Comment by mrshawnho** [comment]
@mustkass 卸载插件重装试试呢

**Comment by mustkass** [comment]
@mrshawnho 嗯嗯，我把IDEA 的配置信息都重新配了一下，然后就好了， 重新安装插件应该也是可以的😁😁
