### ISSUE TITLE
Mybatis Plugin 3.55 会强制 Idea 在 idea.vmoptions 中添加参数 -XX:+DisableAttachMechanism

### ISSUE THREAD

**Issue by moonfruit** [mrshawnho/ideaagent#21]
3.55 的 Mybatis Plugin 会强制 Idea 在 idea.vmoptions 中添加参数 -XX:+DisableAttachMechanism，没有这个参数就阻止 Idea 的启动，同时将这个参数写入 idea.vmoptions。
这个参数貌似阻止了 ideaagent 的加载。

**Comment by mrshawnho** [comment]
今天又看了下确实如此 准备开干了

**Comment by zhaoqin102** [comment]
期待ing

**Comment by ShingmoYeung** [comment]
大神，来个二维码捐助，我能做的就是远远的支持你，请你喝杯咖啡☕️

**Comment by zhaoqin102** [comment]
![image](https://user-images.githubusercontent.com/11658078/37702047-420b034e-2d2c-11e8-994c-e9632781e182.png)
这个应该是写vmoptions的

**Comment by afsfge** [comment]
期待大神更新，同样建议大神来个捐赠二维码

**Comment by Syasuker** [comment]
哈哈哈斗智斗勇~ 谢谢大佬~

**Comment by mrshawnho** [comment]
3.55 稳定性太差 就暂时不搞了 3.53 已经够用了
如升级过 3.55 的同学请删除 VMOptions 文件内的 -XX:+DisableAttachMechanism

**Comment by Syasuker** [comment]
Mybatis Plugin v3.42 请求这个!

**Comment by Lxjazni7** [comment]
3.53 还是会报A network is required to user Mybatis plugin.

**Comment by jinjim** [comment]
删除掉config目录下的.vmoptions文件

**Comment by FreeStyleNight** [comment]
希望可以增加对 IDEA 2018.1 版本的支持，多谢大神

**Comment by yao00jun** [comment]
希望可以增加对 IDEA 2018.1 版本的支持，多谢大神

**Comment by shx1545** [comment]
期待啊

**Comment by ddjoker** [comment]
<idea-version since-build="163.9166" until-build="189.*"/> 测试可以安装

**Comment by ddjoker** [comment]
` <idea-version since-build="163.9166" until-build="189.*"/>`

**Comment by ddjoker** [comment]
但是不能破解 3.5.7

**Comment by ScaredJin** [comment]
@ddjoker 有2018可以支持的版本吗，可以破解的
