### ISSUE TITLE
与2018.1不兼容

### ISSUE THREAD

**Issue by wood4083** [mrshawnho/ideaagent#25]
Plugin 'ideaagent' is incompatible with this installation

**Comment by yao00jun** [comment]
希望可以增加对 IDEA 2018.1 版本的支持，多谢大神

**Comment by Lxjazni7** [comment]
期待 2018.1 + 3.57

**Comment by chinaerserver** [comment]
期待能够兼容2018.1

**Comment by Summerslyb** [comment]
修改plugin.xml就可以在2018.1使用.
相关PR已经被Accept, 但是需要v3.57才支持2018.1
v3.53强行plugin.xml开项目时会报错_(:3」∠)_
v3.57和agent同时用的话, IDEA会卡死.

**Comment by caochuansong** [comment]
@Summerslyb 请问如何修改plugin.xml呢？

**Comment by dylanleung** [comment]
那就是还不能用咯?

**Comment by Summerslyb** [comment]
@caochuansong #26 在这个PR里面
@dylanleung 退回2017.3就可以用了

**Comment by liuji789** [comment]
2018.1不能使用啊

**Comment by shx1545** [comment]
@Summerslyb  但是ideaagent-1.12.zip里并没有修改，有最新的zip包吗

**Comment by Summerslyb** [comment]
改了也没有用的
还是老老实实用2017.3吧

**Comment by litttlefisher** [comment]
期待crack Mybatis plugin v3.57

**Comment by qinkangdeid** [comment]
这个插件还好用的 希望能够破解支持IDEA2018

**Comment by ScaredJin** [comment]
期待最新版的支持

**Comment by sk163** [comment]
希望能尽早支持2018.1……不会卡死的Mybatis plugin

**Comment by yao00jun** [comment]
希望能尽早支持2018.1……不会卡死的Mybatis plugin

**Comment by OuDale** [comment]
希望能尽早支持2018.1……不会卡死的Mybatis plugin

**Comment by mrshawnho** [comment]
v1.2 已发布

**Comment by litttlefisher** [comment]
@mrshawnho perfect!!!

**Comment by litttlefisher** [comment]
@mrshawnho 不要意思，我这边下载试了下，还是没用的
![image](https://user-images.githubusercontent.com/19563352/38453157-bc82b392-3a83-11e8-995e-de3bcb6e5b94.png)
![image](https://user-images.githubusercontent.com/19563352/38453169-dbb37346-3a83-11e8-9481-67fc1d3ba9c9.png)
![image](https://user-images.githubusercontent.com/19563352/38453161-c972feae-3a83-11e8-99c0-5b144d7fa38c.png)
我总结下您这个插件安装步骤吧！
1. idea要先安装了Mybatis Plugin V3.57
2. 下载您发布的ideaagent-1.2.jar包
3. 配置VM Options，其中路径应该是ideaagent-1.2.jar包所放位置
4. 重启IDEA，会弹出一个要认证的弹框，点击Accept

麻烦您看下，是我忽略了什么步骤还是怎么了，我打开工程后，Mybatis Plugin虽说不弹出要输入验证码的Event了，可也还是用不了的

**Comment by mrshawnho** [comment]
@litttlefisher v3.58

**Comment by litttlefisher** [comment]
@mrshawnho 3Q，使用Mybatis plugin v3.58完美解决问题。另外您可以把我上面所写安装步骤放到readme.md中做一个说明。我在安装中会遇到一些坑，我自己尝试了好几次

**Comment by OuDale** [comment]
您好,请问有没有遇到一直报mybatis plugins空指针错误的?
null
java.lang.NullPointerException
	at com.a.b.f.d.C.b(C.java:315)
	at com.a.b.f.x.lambda$processAliases$5(x.java:27)
	at java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:267)
	at java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:948)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
...

**Comment by OuDale** [comment]
@mrshawnho  打扰

**Comment by mrshawnho** [comment]
@OuDale 您是什么环境呢 我这边测试没有报错

**Comment by mrshawnho** [comment]
@OuDale 请贴出IDEA版本和插件列表截图呢

**Comment by OuDale** [comment]
@mrshawnho
![default](https://user-images.githubusercontent.com/35997429/38454970-abc7b9d8-3aa3-11e8-81d0-d140eea596b6.png)
![default](https://user-images.githubusercontent.com/35997429/38454976-caffb418-3aa3-11e8-82b8-c9ecd0e3878b.png)
麻烦您

**Comment by mrshawnho** [comment]
@OuDale 有装其他插件吗？看下~/ideaagent.log有没有报错？试下用管理员身份启动idea呢

**Comment by OuDale** [comment]
@mrshawnho
![default](https://user-images.githubusercontent.com/35997429/38455055-e20ca5d4-3aa4-11e8-8f62-6489451169f3.png)
![default](https://user-images.githubusercontent.com/35997429/38455062-090320e6-3aa5-11e8-8260-bf8cb6fb6bb6.png)
![default](https://user-images.githubusercontent.com/35997429/38455066-1377af6a-3aa5-11e8-8368-10526c193fe3.png)
![default](https://user-images.githubusercontent.com/35997429/38455076-1c5bdc46-3aa5-11e8-857e-61b64d469e00.png)
![default](https://user-images.githubusercontent.com/35997429/38455095-63e7149a-3aa5-11e8-8a47-6a205ec49e07.png)

**Comment by OuDale** [comment]
@mrshawnho
报错还是间歇性的,某一会就不停报,一旦clear之后,马上就报nullPointerException,

**Comment by mrshawnho** [comment]
@OuDale 看起来一切正常啊 mybatis plugin 能用么？

**Comment by OuDale** [comment]
@mrshawnho
频繁报错时就不行.应该不是插件原因,我试过装free版本的也会出现这个问题. 
回头卸载干净再重新安装一下 idea试试.
谢谢您的耐心解答!

**Comment by bisyfish** [comment]
A network is required to use Mybatis plugin. You can configure a proxy if you can't access the internet.
我idea 2017.3  装3.53 报这个错误，2018.1装3.58也是这个错误，有点蒙

**Comment by evenson419** [comment]
刚才试了下，已可完美兼容了。多大大神！

**Comment by bisyfish** [comment]
我那个不能联网问题解决了哈，发现日志报错是不能运行wmic命令，在windows环境变量的path添加相应的路径，wmic指令可以用了后，重启下就可以用了，谢谢大神了

**Comment by BearBig-CN** [comment]
@mrshawnho 多谢了，已验证IDEA2018.1完美支持

**Comment by javahuang** [comment]
@BearBig-CN 您好，能传给我一份 MyBatis-3.58.zip 安装包吗？找不到 3.58 下载的地方了

**Comment by farzer** [comment]
+1 没有3.58的包怎么办

**Comment by icycheng** [comment]
安装好3.58,配置完javaagent直接无法启动idea了...

**Comment by sgt110** [comment]
有3.85的包吗
