### ISSUE TITLE
win7下的idea2018.1怎么设置？设置好了无法启动

### ISSUE THREAD

**Issue by flykarry** [mrshawnho/ideaagent#30]

**Comment by CodingOX** [comment]
重启试试！我在 mac 下第一次也是如此，后面就 ok 了。重启2次成功激活。
mac下可能还要授权给 jar 包。

**Comment by songdl** [comment]
第一次会卡死，结束进程，然后重启dea2018.1二次，一共重启三次。

**Comment by zebraZeng** [comment]
弱弱的问一句，那个下载的jar包放在哪，win7

**Comment by songdl** [comment]
放那里都可以的，然后按说明写明路径和文件名称。

**Comment by johnsonzheng0824** [comment]
@zebraZeng 
放哪都行，用绝对路径

**Comment by zebraZeng** [comment]
谢谢了，我一开始用的相对路径写错了

**Comment by flykarry** [comment]
各位，你们都弄好了吗？重启电脑吗？

**Comment by flykarry** [comment]
我的就是双击桌面图标没反应，不会弹出加载框，怎么点都没反应

**Comment by scott-z** [comment]
起不来一般是路径写错了.

**Comment by flykarry** [comment]
好了，我的也可以了，果然是路径的问题，而且我把idea.exe.vmoptions和idea64.exe.vmoptions都加上了代理路径-javaagent:E:/MyPlugin/ideaagent-1.2.jar

**Comment by a1099259097** [comment]
解决了吗 ，3个地方都要加，才能启动成功吗,我启动不了，直接重装了，现在不敢乱加了

**Comment by mrshawnho** [comment]
感谢同学们帮助
