### ISSUE TITLE
idea 2018.1.1 凉了

### ISSUE THREAD

**Issue by An0nymous0** [mrshawnho/ideaagent#34]
![image](https://user-images.githubusercontent.com/6836030/38611455-4697630e-3db6-11e8-9de8-0f2f905e65b5.png)

**Comment by songdl** [comment]
直接新安装的2018.1.1吧？

**Comment by An0nymous0** [comment]
通过JetBrains Tools更新的，应该算是新装的

**Comment by songpoliu** [comment]
![test](https://user-images.githubusercontent.com/37629096/38627050-95f97674-3de0-11e8-9967-9eda2bf80da9.png)
2018.1.1 测试没问题

**Comment by scott-z** [comment]
2018.1.1 测试没问题
![image](https://user-images.githubusercontent.com/6611983/38651895-221a03b2-3e36-11e8-9dba-2be2101d173f.png)

**Comment by An0nymous0** [comment]
![image](https://user-images.githubusercontent.com/6836030/38653476-8692a860-3e3d-11e8-816c-c53d20bae858.png)

**Comment by songdl** [comment]
@An0nymous0 处用绝对路径吧 C:\Users

**Comment by An0nymous0** [comment]
@songdl 这是mac的绝对路径

**Comment by cxdweirui** [comment]
卡启动，且删掉javaagent后 原使用javaagent方式 无法激活idea

**Comment by mrshawnho** [comment]
并没有凉 多检查配置

**Comment by An0nymous0** [comment]
@mrshawnho 100%确定
![image](https://user-images.githubusercontent.com/6836030/38972436-0bb44e28-43d3-11e8-9c4d-fed695c73b5a.png)路径是没问题的，还有其他配置需要改么？
