### ISSUE TITLE
我配置好了，重启了IDEA，然后得到这个提示

### ISSUE THREAD

**Issue by flykarry** [mrshawnho/ideaagent#37]
![_20180416090201](https://user-images.githubusercontent.com/14309127/38785670-e02b0bf0-4154-11e8-93ee-ed367805f434.png)
接下来我该怎么做？现在这状态是不是没生效？

**Comment by shuohao** [comment]
没生效

**Comment by flykarry** [comment]
那我该咋办？
![_20180418090439](https://user-images.githubusercontent.com/14309127/38906178-9d2ca6d0-42e7-11e8-9e35-2fd33976df13.png)

**Comment by flykarry** [comment]
还是不行啊，我改了config和system目录，然后创建Custom VM Option之后还是自动放在了原有目录，我把ideaagent放在里边，然后怎么都启动不了，我确定路径没写错，咋办？？？

**Comment by flykarry** [comment]
我的路径是 -javaagent:E:/MyPlugin/ideaagent-1.2.jar
