### ISSUE TITLE
使用了之后不能调试了。。。

### ISSUE THREAD

**Issue by evolzzz** [mrshawnho/ideaagent#4]
debug tomcat一直说debugger port打开失败，52588

**Comment by mrshawnho** [comment]
@evolzzz 由于程序默认打开了本地7848端口 你看下tomcat设置的端口是不是冲突了

**Comment by evolzzz** [comment]
奇怪的错误，debug tomcat，tomcat用的127.0.0.1:55400这个端口，应该不会冲突呀。。
（问题是unable to open debugger port 大概这个意思）
我将debug方式从socket换成了shared memory，就行了。
后来再将debug方式从shared memory换成socket，又可以了。

**Comment by farzer** [comment]
所以是能用了？

**Comment by evolzzz** [comment]
对。。。但为啥第一次不能用呢，tomcat调试端口不太可能冲突啊，毕竟50000+的
